;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	c-electric-brace
	c-electric-colon
	c-electric-delete-forward
	c-electric-lt-gt
	c-electric-paren
	c-electric-semi&comma
	c-electric-slash
	c-electric-star
	c-indent-line-or-region
	helm-M-x
	helm-imenu
	helm-mini
	hungry-delete-forward
	indent-for-tab-command
	jump-char-forward
	jump-char-process-char
	keyboard-escape-quit
	kill-region
	mark-sexp
	prelude-move-beginning-of-line
	rectangle-number-lines
	sh-case
	smarter-move-beginning-of-line
	vterm--self-insert
	vterm-send-backspace
	wdired--self-insert
	wdired-finish-edit
	))

(setq mc/cmds-to-run-once
      '(
	helm-swoop
	hungry-delete-backward
	lsp-ui-peek-find-definitions
	rk/copilot-complete-or-accept
	smart-hungry-delete-backward-char
	sp-remove-active-pair-overlay
	))
