;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-delete-forward
        helm-M-x
        helm-imenu
        jump-char-forward
        jump-char-process-char
        mark-sexp
        prelude-move-beginning-of-line
        ))

(setq mc/cmds-to-run-once
      '(
        smart-hungry-delete-backward-char
        ))
