;;; ccls-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from ccls.el

(register-definition-prefixes "ccls" '("ccls-"))


;;; Generated autoloads from ccls-call-hierarchy.el

(register-definition-prefixes "ccls-call-hierarchy" '("ccls-call-hierarchy"))


;;; Generated autoloads from ccls-code-lens.el

(register-definition-prefixes "ccls-code-lens" '("ccls-"))


;;; Generated autoloads from ccls-inheritance-hierarchy.el

(register-definition-prefixes "ccls-inheritance-hierarchy" '("ccls-inheritance-hierarchy"))


;;; Generated autoloads from ccls-member-hierarchy.el

(register-definition-prefixes "ccls-member-hierarchy" '("ccls-member-hierarchy"))


;;; Generated autoloads from ccls-semantic-highlight.el

(register-definition-prefixes "ccls-semantic-highlight" '("ccls-"))


;;; Generated autoloads from ccls-tree.el

(register-definition-prefixes "ccls-tree" '("ccls-tree-"))

;;; End of scraped data

(provide 'ccls-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ccls-autoloads.el ends here
