;;; x509-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from x509-mode.el

(autoload 'x509-mode "x509-mode" "\
Major mode for displaying OpenSSL output.

\\{x509-mode-map}

(fn)" t)
(autoload 'x509-viewcert "x509-mode" "\
Parse current buffer as a certificate file.

With \\[universal-argument] prefix, you can edit the command arguments." t)
(autoload 'x509-viewreq "x509-mode" "\
Parse current buffer as a certificate request file.

With \\[universal-argument] prefix, you can edit the command arguments." t)
(autoload 'x509-viewcrl "x509-mode" "\
Parse current buffer as a CRL file.

With \\[universal-argument] prefix, you can edit the command arguments." t)
(autoload 'x509-viewpkcs7 "x509-mode" "\
Parse current buffer as a PKCS#7 file.

Output only certificates and CRLs by default.  Add the \"-print\"
switch to output details.

With \\[universal-argument] prefix, you can edit the command arguments." t)
(autoload 'x509-viewdh "x509-mode" "\
Parse current buffer as a DH-parameter file.

With \\[universal-argument] prefix, you can edit the command arguments." t)
(autoload 'x509-viewec "x509-mode" "\
Parse current buffer as a EC-parameter file.

With \\[universal-argument] prefix, you can edit the command arguments." t)
(autoload 'x509-viewkey "x509-mode" "\
Display x509 private key using the OpenSSL pkey command.

With \\[universal-argument] prefix, you can edit the command arguments." t)
(autoload 'x509-viewpublickey "x509-mode" "\
Display x509 public key using the OpenSSL pkey command.

With \\[universal-argument] prefix, you can edit the command arguments." t)
(autoload 'x509-viewlegacykey "x509-mode" "\
Display x509 private key using the OpenSSL pkey command.

This function works with older OpenSSL that could not read key from
stdin.  Instead, the buffer file is used with -in.

ARGS are arguments to the openssl command.

With \\[universal-argument] prefix, you can edit the command arguments.
For example to enter pass-phrase, add -passin pass:PASSPHRASE.

(fn &optional ARGS)" t)
(autoload 'x509-dwim-next "x509-mode" "\
Look for a PEM region after the current one.
If found, kill current buffer, switch to src buffer and call `x509-dwim'.
Intended to be called in a `x509-mode' or `x509-asn1-mode' buffer." t)
(autoload 'x509-dwim-prev "x509-mode" "\
Look for a PEM region before the current one.
If found, kill current buffer, switch to src buffer and call `x509-dwim'.
Intended to be called in a `x509-mode' or `x509-asn1-mode' buffer." t)
(autoload 'x509-dwim "x509-mode" "\
Guess the type of object and call the corresponding view-function." t)
(autoload 'x509-swoop "x509-mode" "\
Find all known BEGIN/END PEM regions i buffer and call `x509-dwim'.
For each region, the result is sent to the same `x509-mode' buffer.
Some functions does not work in a swooped buffer, like next/prev or
toggling to and from `x509-asn1-mode'.  The buffer is for static viewing only.

Return view buffer on success." t)
(autoload 'x509-asn1-mode "x509-mode" "\
Major mode for displaying openssl asn1parse output.

\\{x509-asn1-mode-map}

(fn)" t)
(autoload 'x509-viewasn1 "x509-mode" "\
Parse current buffer as ASN.1.

With \\[universal-argument] prefix, you can edit the command arguments." t)
(register-definition-prefixes "x509-mode" '("x509-"))

;;; End of scraped data

(provide 'x509-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; x509-mode-autoloads.el ends here
