;;; helm-system-packages-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from helm-system-packages.el

(autoload 'helm-system-packages "helm-system-packages" "\
Helm user interface for system packages.
By default choose the package manager dedicated to this system, with a
prefix arg allow choosing package manager

(fn &optional ARG)" t)
(register-definition-prefixes "helm-system-packages" '("helm-system-packages-"))


;;; Generated autoloads from helm-system-packages-brew.el

(register-definition-prefixes "helm-system-packages-brew" '("helm-system-packages-brew"))


;;; Generated autoloads from helm-system-packages-dnf.el

(register-definition-prefixes "helm-system-packages-dnf" '("helm-system-packages-dnf"))


;;; Generated autoloads from helm-system-packages-dpkg.el

(register-definition-prefixes "helm-system-packages-dpkg" '("helm-system-packages-"))


;;; Generated autoloads from helm-system-packages-guix.el

(register-definition-prefixes "helm-system-packages-guix" '("helm-system-packages-g"))


;;; Generated autoloads from helm-system-packages-pacman.el

(register-definition-prefixes "helm-system-packages-pacman" '("helm-system-packages-pacman"))


;;; Generated autoloads from helm-system-packages-portage.el

(register-definition-prefixes "helm-system-packages-portage" '("helm-system-packages-portage"))


;;; Generated autoloads from helm-system-packages-xbps.el

(register-definition-prefixes "helm-system-packages-xbps" '("helm-system-packages-xbps"))

;;; End of scraped data

(provide 'helm-system-packages-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; helm-system-packages-autoloads.el ends here
