;;; robot-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from robot-mode.el

(autoload 'robot-mode "robot-mode" "\
Major mode for editing Robot framework files.

\\{robot-mode-map}

(fn)" t)
(add-to-list 'auto-mode-alist '("\\.\\(robot\\|resource\\)\\'" . robot-mode))
(register-definition-prefixes "robot-mode" '("robot-mode-"))

;;; End of scraped data

(provide 'robot-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; robot-mode-autoloads.el ends here
